---
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=111
      - PGID=117
      - TZ=America/Detroit
    volumes:
      - /media/config/lidarr:/config
      - /media:/media
    ports:
      - 8686:8686
    restart: unless-stopped
