---
version: "3.0"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=111
      - PGID=117
      - MYSQL_ROOT_PASSWORD=Oct1982!!
      - TZ=America/Detroit
    volumes:
      - /config/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
