version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oct1982!!
    volumes:
      - /media/config/mysql:/var/lib/mariadb
    ports:
      - 3306:3306
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
