version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oct1982!!
    volumes:
    - mariadb_data:
        driver_opts:
          type: nfs 
          o: addr=10.32.10.11
          device: :/mnt/LFFPool/AV/config/mariadb
    ports:
      - 3306:3306
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
