---
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=111
      - PGID=117
      - TZ=America/Detroit
    volumes:
      - /media/config/radarr:/config
      - /media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
